version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - backend-network
    command: npm run dev

networks:
  backend-network:
    driver: bridge
